task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 1
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/byu-locating-bacterial-flagellar-motors-merged/yolo_dataset/images/train/
    ann_file: /kaggle/input/byu-locating-bacterial-flagellar-motors-merged/yolo_dataset/annotations_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/byu-locating-bacterial-flagellar-motors-merged/yolo_dataset/images/val/
    ann_file: /kaggle/input/byu-locating-bacterial-flagellar-motors-merged/yolo_dataset/annotations_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
